version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-server
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=your_secure_password
    command: >
      redis-server 
      --requirepass your_secure_password
      --appendonly yes
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "your_secure_password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379:0:your_secure_password
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - redis-network

volumes:
  redis_data:
    driver: local

networks:
  redis-network:
    driver: bridge 